name: pyseldonenv
channels:
  - conda-forge

dependencies:
  - meson
  - ninja
  - python
  - pybind11
  - pytest
  - meson-python
  - fmt
  - cmake
  - cpp-argparse
  - clang-format=18.1.1
  - tomlplusplus
  - catch2 
  - pkg-config
  # - pip
  #   - sphinx
  #   - sphinx-design
  #   - sphinxcontrib-napoleon