
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/parrot_user/micromamba/envs/pyseldonenv/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 6.5.0-13parrot1-amd64 - x86_64
...
