name : build pyseldon and test

on: [push, pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: micromamba setup
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        generate-run-shell: true
        cache-environment: true
        init-shell: bash
    - name: build-and-install
      shell: micromamba-shell {0}
      run: |
        meson setup build
        pip install .

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Build the documentation
      run: |
        cd docs
        make html
    - name: Deploy the documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/source/_build/html     
    
    - name: test
      shell: micromamba-shell {0}
      run: |
        pytest tests/